env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
globals:
  JSX: true
settings:
  react:
    version: detect
